language: objective-c
osx_image: beta-xcode6.3
xcode_workspace: Chariz.xcworkspace
xcode_scheme: Chariz

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

notifications:
  slack:
    secure: GafPr/W9TKQF2/oYF0SHHZSrE6OS2ea9+CwEdpgCl2ZDkkvCcFHCyy2SkK4b7cYpqUfEp0Q9+sPQqkmdWyWD+WQAM6IdNNI8xU8/SWcb5hKCanNzfVUwGXk0xhULaLDKr9rtypGZrtkvgenT0JYrh/xTNnNEBU4hkXxplIuSSBo=
